### ISSUE TITLE
mysql database not found when running init.sh

### ISSUE THREAD

**Issue by thekie** [dnhsoft/docker-shopware#4]
Hello,
I use this docker compose file:

```
shop:
  image: dnhsoft/shopware:5.5.4-php7
  links:
   - db
   - mailhog
  volumes:
   - "./../dev:/shopware/custom/plugins/dev"
  ports:
   - "8000:80"

db:
  image: tutum/mysql:5.6
  volumes:
   - ".database:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456

pma:
  image: dnhsoft/phpmyadmin:4.6.0
  links:
   - db
  ports:
   - "8001:80"

mailhog:
  image: mailhog/mailhog
  expose:
   - "1025"
   - "8025"
  ports:
   - "8025:8025"
```

When I run your init.sh (I got this from example 6 "how to develop a plugin"), I see the following:

```
Waiting for mysql server...
Waiting for mysql server...
Waiting for mysql server...
Waiting for mysql server...
Waiting for mysql server...
Waiting for mysql server...
```

It works with `dnhsoft/shopware:5.1.6` …
What do I wrong?
